on:
  push:
    branches: [main]
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22.5
        uses: actions/setup-go@v6
        with:
          go-version: '1.22.5'

      - name: Check Go version
        run: |
          go version
          go env GOVERSION

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.3